version: '3.4'
networks:
  constr-sw-2023-1:
volumes:
  constr-sw-2023-1-keycloak-data:
    external: true
services:
  # Keycloak
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    ports:
      - 8090:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=a12345678
      - KEYCLOAK_FRONTEND_URL=http://localhost:8090/auth
      - KEYCLOAK_IMPORT=/tmp/realm.json
    volumes:
      - ../oauth/data:/opt/jboss/keycloak/standalone/data
      - ../oauth/resources/keycloak/realm.json:/tmp/realm.json
    networks:
      - constr-sw-2023-1
    # healthcheck:
    #      test: [ "CMD-SHELL", "..." ]
    #      start_period: 60s
    #      interval: 20s
    #      timeout: 5s
    #      retries: 5
