version: '3.4'
networks:
  constr-sw-2023-1:
services:
  # Keycloak
  keycloak:
    container_name: keycloak
    build: ./resources/keycloak/.
    image: constr-sw-2023-1/keycloak:latest
    ports:
      - 8090:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=a12345678
      - KEYCLOAK_FRONTEND_URL=http://localhost:8090
      - KC_HEALTH_ENABLED=true
    volumes:
      - ./oauth/src/main/resources/keycloak_data:/opt/jboss/keycloak/standalone/data
      - ./oauth/src/main/resources/keycloak_data:/opt/keycloak/data/import
    networks:
      - constr-sw-2023-1
    command: start-dev --import-realm
    # healthcheck:
    #      test: [ "CMD-SHELL", "curl -f http://localhost:8090/health || exit 1" ]
    #      start_period: 120s
    #      interval: 10s
    #      timeout: 10s
    #      retries: 5
  # OAuth
  oauth:
    container_name: oauth
    build: ./oauth/.
    image: constr-sw-2023-1/oauth:latest
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_CLIENT_ID=oauth
      - KEYCLOAK_CLIENT_SECRET=04bfUatIDO6ipwg1TF2mTzHrX8UZD02Z
      - KEYCLOAK_REALM=construcao-sw
      - KEYCLOAK_REALM_URL=http://keycloak:8080
    networks:
      - constr-sw-2023-1
    depends_on:
      - keycloak
      # keycloak:
      #   condition: service_healthy
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
    #   start_period: 20s
    #   interval: 10s
    #   timeout: 10s
    #   retries: 5
  # Grupo 1 - Backend Courses
  # Grupo 2 - Backend Lessons
  # Grupo 3 - Backend Professors
  # Grupo 4 - Backend Resources
  # Grupo 5 - Backend Rooms
  # Grupo 6 - Backend Classes
  # Grupo 7 - Backend Students
  # Grupo 8 - Backend Reservations

